import "./globals.css";
import { Inter } from "next/font/google";

import { QueryProvider } from "@/providers/react-query";
import { Toaster } from "@/components/toaster";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryProvider>
          <main
            className={cn(
              "mx-auto my-10 w-full max-w-4xl px-4",
              inter.className
            )}
          >
            {children}
            <Toaster />
          </main>
        </QueryProvider>
      </body>
    </html>
  );
}
